from pathlib import Path
import re
p=Path('Gestao_de_Projetos.html')
h=p.read_text(encoding='utf-8')
h=h.replace('<title>CSC Gestão de Projetos | v89</title>','<title>CSC Gestão de Projetos | v90</title>',1)
h=h.replace('const PROJECTS_PER_PAGE = 5;','const PROJECTS_PER_PAGE = 10;')
if 'const REGISTRATION_PER_PAGE = 10;' not in h:
    h=h.replace('const MILESTONES_PER_PAGE = 5;\n    let projectCurrentPage = 1;','const MILESTONES_PER_PAGE = 5;\n    const REGISTRATION_PER_PAGE = 10;\n    let projectCurrentPage = 1;\n    let registrationCurrentPage = 1;',1)
old='''      empty.hidden = true;\n      list.innerHTML = projects.map(project => `'''
new='''      empty.hidden = true;\n      const registrationTotalPages = Math.max(1, Math.ceil(projects.length / REGISTRATION_PER_PAGE));\n      registrationCurrentPage = Math.min(Math.max(1, registrationCurrentPage), registrationTotalPages);\n      const registrationPageStart = (registrationCurrentPage - 1) * REGISTRATION_PER_PAGE;\n      const visibleRegistrationProjects = projects.slice(registrationPageStart, registrationPageStart + REGISTRATION_PER_PAGE);\n      renderRegistrationPagination(registrationTotalPages);\n      list.innerHTML = visibleRegistrationProjects.map(project => `'''
if old in h: h=h.replace(old,new,1)
if 'id="registrationPagination"' not in h:
    pat=re.compile(r'(<div id="registrationEmpty" class="registration-empty">.*?</div>)(\s*</div>)',re.S)
    m=pat.search(h)
    if not m: raise SystemExit('registrationEmpty não localizado')
    h=h[:m.start()]+m.group(1)+'\n              <div id="registrationPagination" class="registration-pagination" hidden></div>'+m.group(2)+h[m.end():]
if 'function renderRegistrationPagination(totalPages)' not in h:
    js='''    function renderRegistrationPagination(totalPages) {\n      const pagination = document.getElementById("registrationPagination");\n      if (!pagination) return;\n      if (!totalPages || totalPages <= 1) { pagination.hidden = true; pagination.innerHTML = ""; return; }\n      pagination.hidden = false;\n      const buttons = [];\n      buttons.push(`<button type="button" class="registration-page-btn" data-registration-page="prev" ${registrationCurrentPage <= 1 ? "disabled" : ""}>‹</button>`);\n      for (let page = 1; page <= totalPages; page += 1) buttons.push(`<button type="button" class="registration-page-btn ${page === registrationCurrentPage ? "active" : ""}" data-registration-page="${page}">${page}</button>`);\n      buttons.push(`<button type="button" class="registration-page-btn" data-registration-page="next" ${registrationCurrentPage >= totalPages ? "disabled" : ""}>›</button>`);\n      pagination.innerHTML = buttons.join("");\n    }\n\n    document.getElementById("registrationPagination")?.addEventListener("click", event => {\n      const button = event.target.closest("[data-registration-page]");\n      if (!button || button.disabled) return;\n      const totalPages = Math.max(1, Math.ceil(projects.length / REGISTRATION_PER_PAGE));\n      const action = button.dataset.registrationPage;\n      if (action === "prev") registrationCurrentPage = Math.max(1, registrationCurrentPage - 1);\n      else if (action === "next") registrationCurrentPage = Math.min(totalPages, registrationCurrentPage + 1);\n      else registrationCurrentPage = Math.min(totalPages, Math.max(1, Number(action) || 1));\n      renderRegistrationList();\n    });\n\n'''
    h=h.replace('    let editingProjectId = null;',js+'    let editingProjectId = null;',1)
oldpop='''          popover.innerHTML = `\n            <strong title="${escapeHtml(projectName)}">${escapeHtml(projectName)}</strong>'''
newpop='''          popover.innerHTML = `\n            <button type="button" class="calendar-popover-close" aria-label="Fechar detalhes" title="Fechar">×</button>\n            <strong title="${escapeHtml(projectName)}">${escapeHtml(projectName)}</strong>'''
h=h.replace(oldpop,newpop)
t='''          popover.classList.add("show");\n          popover.setAttribute("aria-hidden", "false");'''
r='''          popover.classList.add("show");\n          popover.setAttribute("aria-hidden", "false");\n          popover.querySelector(".calendar-popover-close")?.addEventListener("click", closeEvent => {\n            closeEvent.preventDefault(); closeEvent.stopPropagation();\n            popover.classList.remove("show"); popover.setAttribute("aria-hidden", "true");\n          });'''
h=h.replace(t,r)
if 'data-csc-layout-v90' not in h:
    css='''\n  <style data-csc-layout-v90>\n    @media (min-width:1181px){.dashboard-grid{align-items:stretch!important}.right-column{align-self:stretch!important;height:100%!important;max-width:500px!important}.right-column>.panel,.right-column .pie-panel{height:100%!important;min-height:100%!important}.pie-panel-body{min-height:760px!important;height:calc(100% - 58px)!important;display:grid!important;grid-template-rows:1fr 1fr!important;align-content:stretch!important;padding:22px 18px!important}.pie-section{min-height:0!important;grid-template-columns:minmax(155px,.9fr) minmax(170px,1fr)!important;align-content:center!important;gap:18px!important}.pie-chart-wrap-compact{min-height:210px!important}.pie-chart-compact{width:min(188px,100%)!important}.pie-section-side{max-width:250px!important}}\n    .pie-legend{gap:10px!important}.pie-legend-item{font-size:.75rem!important;min-height:30px!important;column-gap:9px!important}.pie-legend-name{max-width:145px!important;font-size:.74rem!important}.pie-legend-value{font-size:.76rem!important;font-weight:850!important;min-width:66px!important}.pie-total-note{font-size:.71rem!important}.registration-pagination{display:flex;align-items:center;justify-content:flex-end;gap:6px;padding:14px 2px 2px}.registration-pagination[hidden]{display:none!important}.registration-page-btn{min-width:32px;height:32px;padding:0 9px;border-radius:8px;border:1px solid rgba(54,142,181,.24);background:rgba(245,251,253,.74);color:#426779;font:inherit;font-size:.72rem;font-weight:750;cursor:pointer}.registration-page-btn.active{background:#438faa;color:#fff;border-color:#438faa}.registration-page-btn:disabled{opacity:.38;cursor:default}.calendar-date-popover{position:fixed}.calendar-popover-close{position:absolute;top:8px;right:8px;width:26px;height:26px;border-radius:8px;border:1px solid rgba(46,132,170,.24);background:rgba(244,250,253,.92);color:#36718c;display:grid;place-items:center;font-size:18px;line-height:1;cursor:pointer;z-index:2}.calendar-date-popover>strong{padding-right:30px;display:block}\n    @media(max-width:1180px){.pie-panel-body{min-height:0!important;height:auto!important}}\n  </style>\n'''
    h=h.replace('</head>',css+'</head>',1)
p.write_text(h,encoding='utf-8')
